spring:
  application:
    name: umbrella
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none